#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionInventario.Formularios
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;


    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "BDComercial")]
    public partial class ModeloProductosDataContext : System.Data.Linq.DataContext
    {

        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        #region Definiciones de métodos de extensibilidad
        partial void OnCreated();
        partial void InsertProductos(Productos instance);
        partial void UpdateProductos(Productos instance);
        partial void DeleteProductos(Productos instance);
        #endregion

        public ModeloProductosDataContext() :
                base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConexionBDProyecto"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

        public ModeloProductosDataContext(string connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public ModeloProductosDataContext(System.Data.IDbConnection connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public ModeloProductosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public ModeloProductosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public System.Data.Linq.Table<Productos> Productos
        {
            get
            {
                return this.GetTable<Productos>();
            }
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.actualizarProductos")]
        public int actualizarProductos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> valorunitario)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo, nombre, cantidad, valorunitario);
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.buscarProductos")]
        public ISingleResult<buscarProductosResult> buscarProductos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> codigo)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo);
            return ((ISingleResult<buscarProductosResult>)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.eliminarProductos")]
        public int eliminarProductos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> codigo)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo);
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.insertarProductos")]
        public int insertarProductos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> valorunitario)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo, nombre, cantidad, valorunitario);
            return ((int)(result.ReturnValue));
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.Productos")]
    public partial class Productos : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _codigo;

        private string _nombre;

        private System.Nullable<int> _cantidad;

        private System.Nullable<int> _valorunitario;

        #region Definiciones de métodos de extensibilidad
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OncodigoChanging(int value);
        partial void OncodigoChanged();
        partial void OnnombreChanging(string value);
        partial void OnnombreChanged();
        partial void OncantidadChanging(System.Nullable<int> value);
        partial void OncantidadChanged();
        partial void OnvalorunitarioChanging(System.Nullable<int> value);
        partial void OnvalorunitarioChanged();
        #endregion

        public Productos()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_codigo", DbType = "Int NOT NULL", IsPrimaryKey = true)]
        public int codigo
        {
            get
            {
                return this._codigo;
            }
            set
            {
                if ((this._codigo != value))
                {
                    this.OncodigoChanging(value);
                    this.SendPropertyChanging();
                    this._codigo = value;
                    this.SendPropertyChanged("codigo");
                    this.OncodigoChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_nombre", DbType = "NVarChar(50)")]
        public string nombre
        {
            get
            {
                return this._nombre;
            }
            set
            {
                if ((this._nombre != value))
                {
                    this.OnnombreChanging(value);
                    this.SendPropertyChanging();
                    this._nombre = value;
                    this.SendPropertyChanged("nombre");
                    this.OnnombreChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_cantidad", DbType = "Int")]
        public System.Nullable<int> cantidad
        {
            get
            {
                return this._cantidad;
            }
            set
            {
                if ((this._cantidad != value))
                {
                    this.OncantidadChanging(value);
                    this.SendPropertyChanging();
                    this._cantidad = value;
                    this.SendPropertyChanged("cantidad");
                    this.OncantidadChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_valorunitario", DbType = "Int")]
        public System.Nullable<int> valorunitario
        {
            get
            {
                return this._valorunitario;
            }
            set
            {
                if ((this._valorunitario != value))
                {
                    this.OnvalorunitarioChanging(value);
                    this.SendPropertyChanging();
                    this._valorunitario = value;
                    this.SendPropertyChanged("valorunitario");
                    this.OnvalorunitarioChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    public partial class buscarProductosResult
    {

        private int _codigo;

        private string _nombre;

        private System.Nullable<int> _cantidad;

        private System.Nullable<int> _valorunitario;

        public buscarProductosResult()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_codigo", DbType = "Int NOT NULL")]
        public int codigo
        {
            get
            {
                return this._codigo;
            }
            set
            {
                if ((this._codigo != value))
                {
                    this._codigo = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_nombre", DbType = "NVarChar(50)")]
        public string nombre
        {
            get
            {
                return this._nombre;
            }
            set
            {
                if ((this._nombre != value))
                {
                    this._nombre = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_cantidad", DbType = "Int")]
        public System.Nullable<int> cantidad
        {
            get
            {
                return this._cantidad;
            }
            set
            {
                if ((this._cantidad != value))
                {
                    this._cantidad = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_valorunitario", DbType = "Int")]
        public System.Nullable<int> valorunitario
        {
            get
            {
                return this._valorunitario;
            }
            set
            {
                if ((this._valorunitario != value))
                {
                    this._valorunitario = value;
                }
            }
        }
    }
}
#pragma warning restore 1591
